### PR TITLE
Configure CI

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Hello!

As a first step to improve maintainance of this library, I'd like to enable Continuous Integration on it. Here adding configuration files for Travis CI and Appveyor, but as a repo owner you need to enable them yourself.

I'm testing against MRI 2.0+ here, but as a second step, I would drop support for all EOL'd rubies.

Thoughts?

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Builds in my fork: [Travis](https://travis-ci.org/deivid-rodriguez/rb-readline/builds/327758425) and [Appveyor](https://ci.appveyor.com/project/deivid-rodriguez/rb-readline/build/1.0.23).

**Comment by ConnorAtherton** [comment]
@deivid-rodriguez Great addition, and something that should have been done a while back. Can we just keep the travis file, though, as that's the CI I usually have configured on all my projects.

**Comment by deivid-rodriguez** [comment]
I think you should enable Appveyor as well since this library is mainly used by Windows users and that's the CI service to be used to test under Windows.

**Comment by deivid-rodriguez** [comment]
ping @ConnorAtherton

**Comment by deivid-rodriguez** [comment]
Closing since @larskanis' approach of trying to add upstream support seems like the better way to go!

**Comment by deivid-rodriguez** [comment]
I probably should've added a few links about why I closed this PR. In https://github.com/oneclick/rubyinstaller2/issues/93, @larskanis started some work on ruby-core's readline to add better support for windows. So that sounded like a good direction to follow.

However, that worked hasn't moved forward so it sounds like a CI setup wouldn't hurt this gem in the meantime anyways.

**Comment by deivid-rodriguez** [comment]
I reopened this PR, @ConnorAtherton what do you think?

**Comment by deivid-rodriguez** [comment]
Friendly ping after 10 days :smiley:.

**Comment by deivid-rodriguez** [comment]
I have added 2.6.0 as well, since it has been recently been released.

@ConnorAtherton Are you still interested in maintaining this repo?

**Comment by deivid-rodriguez** [comment]
Wellcome to this PR's monthly ping! This is february edition! :smiley:

**Comment by deivid-rodriguez** [comment]
Sounds like there's some progress around this matter and ruby will incorporate a pure ruby readline implementation inside the core. It's https://github.com/ruby/reline.

/cc @aycabta

**Pull request closed without merging**
